server:
  servlet:
    context-path: /my-docs
    multipart:
      enabled: true
      file-size-threshold: 512KB
      max-file-size: 5MB
      max-request-size: 5MB

google:
  secret:
    key.path: classpath:keys/gd_client_secret.json
  oauth:
    callback.uri: http://127.0.0.1.nip.io:8080/my-docs/oauth
